### Create Farm
POST http://localhost:3000/api/v1/farm
content-type: application/json

{
    "name": "criado-via-api",
    "land_area": 48.5,
    "unit": "acre",
    "address": "120 teresina",
    "crops": [
        {
            "crop_type": "BEANS",
            "is_irrigated": true,
            "is_insured": false
        },
        {
            "crop_type": "CORN",
            "is_irrigated": true,
            "is_insured": false
        }
    ]
}

### Delete Farm
DELETE http://localhost:3000/api/v1/farm/675b9d55c9e77a1eff0945c0

### Get Farms
GET http://localhost:3000/api/v1/farm?skip=0&perpage=10