basePath: /
definitions:
  crop.CropDto:
    properties:
      crop_type:
        type: string
      is_insured:
        type: boolean
      is_irrigated:
        type: boolean
    type: object
  farm.FarmDto:
    properties:
      _id:
        type: string
      address:
        type: string
      crops:
        items:
          $ref: '#/definitions/crop.CropDto'
        type: array
      land_area:
        type: number
      name:
        type: string
      unit:
        type: string
    type: object
  shared.ErrorResponse:
    properties:
      details:
        type: string
      message:
        type: string
    type: object
  shared.SuccessResponse:
    properties:
      data:
        type: string
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Tech challenge API
  title: GO-TECH-CHALLENGE
  version: "1.0"
paths:
  /farm:
    get:
      consumes:
      - application/json
      description: This endpoint allows the retrieval of a list of farms, with optional
        query parameters for filtering by name, unit, crop type, and land area. The
        response supports pagination with the 'skip' and 'perpage' parameters. If
        no farms are found, an empty array will be returned. If the required parameters
        are missing or invalid, appropriate error responses will be returned.
      parameters:
      - description: Number of items to skip for pagination
        in: query
        name: skip
        type: integer
      - description: Number of items per page for pagination
        in: query
        name: perpage
        type: integer
      - description: Name of the farm
        in: query
        name: name
        type: string
      - description: Unit for land area
        in: query
        name: unit
        type: string
      - description: Type of crop grown on the farm
        in: query
        name: croptype
        type: string
      - description: Initial land area for filtering
        in: query
        name: landareainit
        type: string
      - description: Limit land area for filtering
        in: query
        name: landarealimit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of farms retrieved successfully
          schema:
            $ref: '#/definitions/shared.SuccessResponse'
        "400":
          description: 'Bad Request: Missing or invalid query parameters'
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: 'Internal Server Error: Error retrieving farms'
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Retrieve a list of farms with optional filters
      tags:
      - Farm
    post:
      consumes:
      - application/json
      description: This endpoint allows the creation of a new farm by providing the
        necessary details.
      parameters:
      - description: Farm Information
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/farm.FarmDto'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created farm
          schema:
            $ref: '#/definitions/shared.SuccessResponse'
        "400":
          description: 'Bad Request: Invalid request payload'
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: 'Internal Server Error: Error initializing or executing farm
            creation process'
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Create a new farm
      tags:
      - Farm
  /farm/{id}:
    delete:
      consumes:
      - application/json
      description: This endpoint allows the deletion of an existing farm by providing
        its unique ID. If the farm is found, it will be deleted. If the farm is not
        found or an error occurs during deletion, appropriate error responses are
        returned.
      parameters:
      - description: Farm ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted farm
          schema:
            $ref: '#/definitions/shared.SuccessResponse'
        "400":
          description: 'Bad Request: Farm ID is required or invalid'
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
        "500":
          description: 'Internal Server Error: Error initializing or executing farm
            deletion'
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: Delete a farm by its ID
      tags:
      - Farm
schemes:
- http
swagger: "2.0"
